ekf_node:
  ros__parameters:
    qos_overrides./odom.publisher.reliability: best_effort
    qos_overrides./accel.publisher.reliability: best_effort

    frequency: 10.0
    # sensor_timeout: 20.0
    use_sim_time: false

    two_d_mode: false

    # transform_time_offset: 0.25
    # transform_timeout: 3.0

    print_diagnostics: true
    debug: false

    permit_corrected_publication: false
    publish_acceleration: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /crazyflie/visual_odometry
    odom0_config: [
        # position
        true,
        true,
        true,

        # orientation
        false,
        false,
        false,

        # lineal vel
        false,
        false,
        false,

        # angular vel
        false,
        false,
        false,

        # lineal acc
        false,
        false,
        false,
      ]
    odom0_queue_size: 5
    # odom0_nodelay: false
    odom0_differential: true
    odom0_relative: false
    # odom0_pose_rejection_threshold: 5.0
    # odom0_twist_rejection_threshold: 1.0

    imu0: /crazyflie/imu_with_covariance
    imu0_config: [ false, false, false,   # x, y, z  
                   true, true, true,    # roll, pitch, yaw
                   false, false, false,   # x vel, y vel, z vel  
                   true, true, true,    # roll vel, pitch vel, yaw vel  
                   true, true, true]     # x accel, y accel, z accel
    # imu0_nodelay: false
    imu0_differential: true
    imu0_relative: false
    # imu0_queue_size: 5
    # imu0_pose_rejection_threshold: 0.8
    # imu0_twist_rejection_threshold: 0.8
    # imu0_linear_acceleration_rejection_threshold: 0.8
    imu0_remove_gravitational_acceleration: true

    # use_control: false
    # stamped_control: false
    # control_timeout: 0.2
    # control_config: [true, false, false, false, false, true]
    # acceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 3.4]
    # deceleration_limits: [1.3, 0.0, 0.0, 0.0, 0.0, 4.5]
    # acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
    # deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]

    process_noise_covariance: [ 1e-3,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,        # x
                                0.0,    1e-3,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,        # y
                                0.0,    0.0,    1e-3,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,        # z
                                0.0,    0.0,    0.0,    1e-3,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,        # roll
                                0.0,    0.0,    0.0,    0.0,    1e-3,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,        # pitch
                                0.0,    0.0,    0.0,    0.0,    0.0,    1e-3,   0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,        # yaw
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-3,   0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,        # x vel
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     1e-3,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,        # y vel
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     1e-3,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,        # z vel
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    1e-3,   0.0,    0.0,    0.0,    0.0,    0.0,        # roll vel
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    1e-3,   0.0,    0.0,    0.0,    0.0,        # pitch vel
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    1e-3,  0.0,    0.0,    0.0,        # yaw vel
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    1e-3,   0.0,    0.0,        # ax
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    1e-3,  0.0,        # ay
                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-3 ]      # az

    initial_estimate_covariance: [ 1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    # x
                                   0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    # y
                                   0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    # z
                                   0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    # roll
                                   0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    # pitch
                                   0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    # yaw
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    # x vel
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    # y vel
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,   0.0,     0.0,     0.0,     0.0,    0.0,    0.0,    # z vel
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,    0.0,     0.0,     0.0,    0.0,    0.0,    # roll vel
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     1e-9,    0.0,     0.0,    0.0,    0.0,    # pitch vel
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     1e-9,    0.0,    0.0,    0.0,    # yaw vel
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     1e-9,   0.0,    0.0,    # ax
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    1e-9,   0.0,    # ay
                                   0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    1e-9 ]  # az