%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 688.63609
Camera.fy: 688.63609
Camera.cx: 320.0
Camera.cy: 240.0

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

# Camera frames per second 
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Camera resolution
Camera.width: 640
Camera.height: 480

# Transformation from camera to body-frame (imu)
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-1.0, 0.0, 0.0, 0.0,
           0.0, 0.0,-1.0, 0.0,
           0.0,-1.0, 0.0, 0.0,
           0.0, 0.0, 0.0, 1.0]

#   data: [-1.0, 0.0, 0.0, 0.0,
#           0.0, 0.0,-1.0, 0.0,
#           0.0,-1.0, 0.0, 0.0,
#           0.0, 0.0, 0.0, 1.0]
#  data: [ 1.0, 0.0, 0.0, 0.0,
#           0.0, 1.0, 0.0, 0.0,
#           0.0, 0.0, 1.0, 0.0,
#           0.0, 0.0, 0.0, 1.0]

# IMU noise parameters
IMU.NoiseGyro: 0.0 # 1.6968e-04 
IMU.NoiseAcc:  0.0 # 2.0000e-3
IMU.GyroWalk:  0.0
IMU.AccWalk:   0.0 # 3.0000e-3
IMU.Frequency: 30

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500